### ISSUE TITLE
[Feature Request] Clickthrough transparency

### ISSUE THREAD

**Issue by vans163** [passingthru67/workspaces-to-dock#113] opened 2017-09-15 03:50 UTC
If you set the opacity to 0%, making the workspace-thumbnails invisible, you cannot click in the empty space, the extension still receives the click.  It would be really useful if you can click on things behind the invisible layer.

Another useful feature to go along with this, is to prevent when dragging windows towards the dock from sticking as they tend to always auto maximize. Its really annoying when your dragging a window and you touch the dock, next thing you know it automaximized.

**Comment by balderclaassen** [comment] 2017-09-18 18:25
Transparency is by definition a visual thing, and therefore not clickthrough-able I don't know if what you're asking is technically possible.

It shouldn't auto maximize unless you release the mouse button. I might be misunderstanding you, but if it maximizes as you're dragging that sounds like a bug more than the lack of a feature. Doesn't work like that for me anyway.

**Comment by vans163** [comment] 2017-09-18 18:32
@balderclaassen the auto-maximize is 2 part (edge-tiling), 1 part is able to be disabled by gconf setting.  Second part is the edges stick as you drag, has been filed as a bug for years, there is no override option to enable/disable this behavior.  The only way is to patch mutter and recompile it / hook funcs in running mutter.

The transparency the best example I can give is this: https://i.imgur.com/CfVqdhC.jpg.

Notice the workspaces-to-dock plugin on the right. if I set opacity to 0, the right grey area that wraps the thumbnails will be invisible.  But if there is a window behind it, the window wont receive any clicks!  It gets confusing as to why you cant click, so I increased the opacity slightly to be able to see the clickable area.

**Comment by balderclaassen** [comment] 2017-09-18 18:44
Would setting the dock to Autosize make it as small as those 2 workspaces and solve your problem? If you don't want to see it anyway.

**Comment by vans163** [comment] 2017-09-18 18:59
@balderclaassen There is still a small frame around it, and between the workspaces. And its positioned poorly when auto size is on.  I cant get it to keep a fixed position starting at that location, and not dynamically sliding up/down each time as a virtual workspace appears or closes.

**Comment by passingthru67** [comment] 2017-09-18 19:16
The transparency 'issue' is by design because the dock (even when transparent) needs to be able to detect mouse pressure, mouse clicks and scroll events. I'll consider the change, though, when I make the updates for issue #98 (which is actually a feature).

**Comment by vans163** [comment] 2017-09-18 19:37
@passingthru67, got it, for that feature I guess it would be possible to not only center it, but anchor/align it to the top/bottom, with a margin?  I find it really hard to position the virtual workspaces to be exactly where I want them to (about 15-20% from the top, and fixed never moving, new workspaces open under)

Thanks and great extension, my favorite.

**Comment by passingthru67** [comment] 2017-10-26 20:08
@vans163: I just committed code to the 'feature-dock-centering' branch that provides advanced centering options. The dock autosize option is no longer tied to dock centering. Give it a try and let me know if it works.

**Closed** 2018-04-28 13:28 UTC
Labels: enhancement
