### ISSUE TITLE
Does not work on Gnome 3.30

### ISSUE THREAD

**Issue by silviobierman** [passingthru67/workspaces-to-dock#149] opened 2018-08-17 07:41 UTC
Ubuntu 18.10 has moved to Gnome shell 3.29.90. The extension has stopped working. I had to uninstall to be able to use my desktop. Please update the extension.

**Comment by silviobierman** [comment] 2018-08-20 07:58
Mine is an 18.04 install that was upgraded to 18.10 about a week agousing "do-release-upgrade -d". Since then I did the occasional "apt update && apt upgrade" and suddenly I was on 3.29.90. Both Workspaces to dock and Dash to dock immediately stopped working.
Moving to the master branch of D2D fixed that part. Since I am an avid workspaces user I am very keen on getting W2D upgraded.
Thanks in advance for all your efforts.

**Comment by passingthru67** [comment] 2018-08-22 15:51
@silviobierman I just uploaded a gnome-3.30-beta branch. Please download and let me know how it works.

**Comment by silviobierman** [comment] 2018-08-22 22:02
@passingthru67: I have just installed the beta and at first sight it seems to be working. The dock left edge looks a little different. The current workspace seems to be highlighted differently (a highlight in the dock left border which I think looked differently and IMHO better).
My compliments for creating a running version this fast. I will keep using/testing it the coming days and if I run into things I will report back here. Thanks a lot!

**Comment by passingthru67** [comment] 2018-08-22 23:06
@silviobierman out of curiosity, would you post a screenshot of what looks different? Also, what gnome-shell theme do you use?

**Comment by passingthru67** [comment] 2018-08-23 11:43
Yes, I see the same thing. I believe it's a new look (at least in Ubuntu). If you disable WtD you'll find that the gnome-shell workspace thumbnails (in activities overview) looks the same way.

**Comment by silviobierman** [comment] 2018-08-24 07:31
I was already afraid that was the case. Too bad but I can live with that.

I took your word for it by the way. Disabling WtD and going with Gnome default is more than I can bare. I was a Unity guy (after initially hating it of course) and when I had to switch to Gnome I was really horrified with the desktop. That is, until I discovered WtD and DtD that make it even better than Unity ever was IMHO. Thanks a lot!

**Comment by passingthru67** [comment] 2018-08-27 14:39
The gnome-3.30-beta branch has been merged so that the master branch now supports Gnome 3.30. Please note that the master branch is not backward compatible with earlier Gnome releases. Gnome 3.28 users should use gnome-3.28 branch.

**Comment by silviobierman** [comment] 2018-09-06 07:31
My machine was just updated to Gnome shell 3.30 (from 3.29.90) and I can confirm the extension still works fine.

**Comment by demokritos** [comment] 2018-09-08 20:00
I got `gnome-shell[1651]: Extension "workspaces-to-dock@passingthru67.gmail.com" had error: SyntaxError: missing ) after catch` and the extension doesn't work.
I don't know which catch it means.
My system is Arch Linux, Gnome 3.30.

**Comment by demokritos** [comment] 2018-09-08 23:06
For me, syntax like `catch(e if e instanceof Gio.IOErrorEnum) { ... }` does not work.
Changing these codes to `catch(e) { if (e instanceof Gio.IOErrorEnum) { ... } }` makes the extension work.

**Comment by passingthru67** [comment] 2018-09-08 23:40
@demokritos, would you provide the module and line#? Better yet, would you provide a dump of your journal log where the error occurs?

**Comment by demokritos** [comment] 2018-09-09 00:16
`catch` is used only in `placeDisplay.js`.
Here is my patch: [workspaces-to-dock.330.patch.txt](https://github.com/passingthru67/workspaces-to-dock/files/2363832/workspaces-to-dock.330.patch.txt)
I untabified code, so the patch includes unrelated parts.

journal log: [workspaces-to-dock.log.txt](https://github.com/passingthru67/workspaces-to-dock/files/2363837/workspaces-to-dock.log.txt)

**Comment by passingthru67** [comment] 2018-09-10 13:06
Patch has been merged into master branch and a new version of WtD has been submitted to Extensions.gnome.org.

The list of extensions that need to be reviewed is growing after Gnome 3.30 was released (https://extensions.gnome.org/review), but hopefully, WtD will be available on their site soon.

**Comment by demokritos** [comment] 2018-09-12 12:37
On gnome-shell 3.30, it seems that WtD crashes gnome-shell when the system is suspended. So when resuming the system, I cannot see the unlock prompt. It shows just grey dumb screen. If the system sleeps and wakes again, this time is OK, but workspace thumbnail is blank.

In login:
```
 9월 12 21:02:34 lettuce gnome-shell[1690]: Object St.BoxLayout (0x559f8620f140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: == Stack trace for context 0x559f836ba280 ==
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #0   7ffca0d253d0 b   resource:///org/gnome/gjs/modules/overrides/GObject.js:468 (7fd74afcc040 @ 25)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #1   559f83bfed40 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/convenience.js:124 (7fd724edd310 @ 91)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #2   7ffca0d262c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #3   559f83bfecb8 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:1615 (7fd724eedc10 @ 60)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #4   7ffca0d271b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #5   7ffca0d27270 b   self-hosted:977 (7fd74afedf70 @ 413)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #6   7ffca0d27360 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #7   559f83bfec30 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1664 (7fd724131040 @ 52)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #8   7ffca0d28250 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #9   7ffca0d28310 b   self-hosted:977 (7fd74afedf70 @ 413)
 9월 12 21:02:34 lettuce dbus-daemon[1646]: [session uid=1000 pid=1646] Successfully activated service 'org.gnome.evolution.dataserver.AddressBook9'
 9월 12 21:02:34 lettuce systemd[1622]: Started Evolution address book service.
 9월 12 21:02:34 lettuce gnome-shell[1690]: Object St.BoxLayout (0x559f8620f140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: == Stack trace for context 0x559f836ba280 ==
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #0   7ffca0d24d10 b   resource:///org/gnome/gjs/modules/overrides/GObject.js:468 (7fd74afcc040 @ 25)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #1   7ffca0d258f0 b   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/convenience.js:124 (7fd724edd310 @ 91)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #2   7ffca0d262c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #3   559f83bfecb8 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:1615 (7fd724eedc10 @ 60)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #4   7ffca0d271b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #5   7ffca0d27270 b   self-hosted:977 (7fd74afedf70 @ 413)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #6   7ffca0d27360 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #7   559f83bfec30 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1664 (7fd724131040 @ 52)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #8   7ffca0d28250 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:02:34 lettuce org.gnome.Shell.desktop[1690]: #9   7ffca0d28310 b   self-hosted:977 (7fd74afedf70 @ 413)
```
In suspend:
```
 9월 12 21:06:24 lettuce systemd-logind[989]: Power key pressed.
 9월 12 21:06:24 lettuce NetworkManager[985]: <info>  [1536753984.8674] manager: sleep: sleep requested (sleeping: no  enabled: yes)
 9월 12 21:06:24 lettuce NetworkManager[985]: <info>  [1536753984.8676] device (): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
 9월 12 21:06:24 lettuce ModemManager[982]: [/dev/cdc-wdm0] channel destroyed
 9월 12 21:06:24 lettuce NetworkManager[985]: <info>  [1536753984.8690] device (): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
 9월 12 21:06:24 lettuce NetworkManager[985]: <info>  [1536753984.8702] device (cdc-wdm0): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
 9월 12 21:06:24 lettuce NetworkManager[985]: <info>  [1536753984.8712] manager: NetworkManager state is now ASLEEP
 9월 12 21:06:24 lettuce gnome-software[1941]: no app for changed caffeine@patapon.info
 9월 12 21:06:24 lettuce gnome-shell[1690]: Object St.BoxLayout (0x559f8620f140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: == Stack trace for context 0x559f836ba280 ==
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #0   7ffca0d1b560 b   resource:///org/gnome/gjs/modules/overrides/GObject.js:468 (7fd74afcc040 @ 25)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #1   559f86c0f3c0 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/convenience.js:124 (7fd724edd310 @ 91)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #2   7ffca0d1c4d0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #3   559f86c0f328 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:1704 (7fd724eedd30 @ 400)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #4   7ffca0d1d440 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #5   7ffca0d1d510 b   self-hosted:979 (7fd74afedf70 @ 440)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #6   7ffca0d1d600 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #7   559f86c0f268 i   resource:///org/gnome/shell/ui/extensionSystem.js:101 (7fd74ac54790 @ 727)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #8   559f86c0f1e8 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7fd74ac59310 @ 13)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #9   7ffca0d1e5a0 b   self-hosted:261 (7fd74afc1dc0 @ 223)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #10   559f86c0f168 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7fd74ac59280 @ 64)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #11   559f86c0f0e8 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7fd74ac593a0 @ 87)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #12   7ffca0d1f6d0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #13   7ffca0d202c0 b   resource:///org/gnome/shell/ui/sessionMode.js:206 (7fd74ab40ee0 @ 254)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #14   7ffca0d20f30 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #15   559f86c0efa8 i   resource:///org/gnome/shell/ui/sessionMode.js:168 (7fd74ab40ca0 @ 40)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #16   7ffca0d21ea0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #17   559f86c0ef00 i   resource:///org/gnome/shell/ui/screenShield.js:1279 (7fd74ab23c10 @ 188)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #18   7ffca0d22e10 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #19   559f86c0ee50 i   resource:///org/gnome/shell/ui/screenShield.js:1328 (7fd74ab23ca0 @ 391)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #20   7ffca0d23d80 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #21   559f86c0edc8 i   resource:///org/gnome/shell/ui/screenShield.js:731 (7fd74ab22670 @ 57)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #22   7ffca0d24cf0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #23   559f86c0ed08 i   self-hosted:979 (7fd74afedf70 @ 440)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #24   7ffca0d25c90 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #25   559f86c0eb90 i   resource:///org/gnome/shell/misc/loginManager.js:225 (7fd74ac10160 @ 158)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #26   7ffca0d26930 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #27   559f86c0ead0 i   self-hosted:981 (7fd74afedf70 @ 474)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #28   559f86c0ea00 i   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:06:24 lettuce org.gnome.Shell.desktop[1690]: #29   559f86c0e960 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:117 (7fd74afb8c10 @ 39)
 9월 12 21:06:25 lettuce gnome-shell[1690]: Removed: 6
```
In the second suspend:
```
9월 12 21:07:05 lettuce systemd-logind[989]: Power key pressed.
 9월 12 21:07:05 lettuce ModemManager[982]: <info>  [device /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4] creating modem with plugin 'Sierra' and '5' ports
 9월 12 21:07:05 lettuce ModemManager[982]: <warn>  Could not grab port (tty/ttyACM1): 'Cannot add port 'tty/ttyACM1', unhandled serial type'
 9월 12 21:07:05 lettuce ModemManager[982]: <info>  Modem for device '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-4' successfully created
 9월 12 21:07:05 lettuce ModemManager[982]: opening device...
 9월 12 21:07:05 lettuce ModemManager[982]: [/dev/cdc-wdm0] Read max control message size from descriptors file: 512
 9월 12 21:07:05 lettuce NetworkManager[985]: <info>  [1536754025.4358] manager: sleep: sleep requested (sleeping: no  enabled: yes)
 9월 12 21:07:05 lettuce NetworkManager[985]: <info>  [1536754025.4360] device (): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
 9월 12 21:07:05 lettuce ModemManager[982]: [/dev/cdc-wdm0] channel destroyed
 9월 12 21:07:05 lettuce NetworkManager[985]: <info>  [1536754025.4367] device (): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
 9월 12 21:07:05 lettuce NetworkManager[985]: <info>  [1536754025.4373] manager: NetworkManager state is now ASLEEP
 9월 12 21:07:05 lettuce gnome-shell[1690]: Object St.BoxLayout (0x559f8620f140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: == Stack trace for context 0x559f836ba280 ==
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #0   7ffca0d1a4b0 b   resource:///org/gnome/gjs/modules/overrides/GObject.js:468 (7fd74afcc040 @ 25)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #1   7ffca0d1a560 b   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/convenience.js:124 (7fd724edd310 @ 91)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #2   7ffca0d1a630 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #3   559f8502bfe8 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/convenience.js:96 (7fd724edd160 @ 55)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #4   7ffca0d1b590 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #5   559f8502bf60 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:646 (7fd724ee9700 @ 131)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #6   7ffca0d1c4f0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #7   559f8502bee0 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:107 (7fd724ed1700 @ 75)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #8   559f8502be20 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7fd74ac54790 @ 436)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #9   559f8502bda0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7fd74ac59310 @ 13)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #10   7ffca0d1d630 b   self-hosted:261 (7fd74afc1dc0 @ 223)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #11   559f8502bd20 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7fd74ac59280 @ 64)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #12   559f8502bca0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7fd74ac593a0 @ 87)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #13   7ffca0d1e760 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #14   7ffca0d1f350 b   resource:///org/gnome/shell/ui/sessionMode.js:206 (7fd74ab40ee0 @ 254)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #15   7ffca0d1ffc0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #16   559f8502bb60 i   resource:///org/gnome/shell/ui/sessionMode.js:168 (7fd74ab40ca0 @ 40)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #17   7ffca0d20f30 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #18   559f8502bac8 i   resource:///org/gnome/shell/ui/screenShield.js:1038 (7fd74ab230d0 @ 421)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #19   7ffca0d21ea0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #20   559f8502ba20 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (7fd74ab23c10 @ 223)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #21   7ffca0d22e10 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #22   559f8502b970 i   resource:///org/gnome/shell/ui/screenShield.js:1328 (7fd74ab23ca0 @ 391)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #23   7ffca0d23d80 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #24   559f8502b8e8 i   resource:///org/gnome/shell/ui/screenShield.js:731 (7fd74ab22670 @ 57)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #25   7ffca0d24cf0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #26   559f8502b828 i   self-hosted:979 (7fd74afedf70 @ 440)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #27   7ffca0d25c90 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #28   559f8502b6b0 i   resource:///org/gnome/shell/misc/loginManager.js:225 (7fd74ac10160 @ 158)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #29   7ffca0d26930 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #30   559f8502b5f0 i   self-hosted:981 (7fd74afedf70 @ 474)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #31   559f8502b520 i   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:07:05 lettuce org.gnome.Shell.desktop[1690]: #32   559f8502b480 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:117 (7fd74afb8c10 @ 39)
 9월 12 21:07:05 lettuce gnome-shell[1690]: Removed: 6
```
In wake:
```9월 12 21:07:29 lettuce gnome-shell[1690]: Object Gio.Settings (0x559f861ed170), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: == Stack trace for context 0x559f836ba280 ==
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #0   559f84f400a0 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/intellihide.js:293 (7fd724edd550 @ 75)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #1   7ffca0d1ea30 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #2   559f84f40020 i   /usr/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:106 (7fd724ed1700 @ 59)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #3   559f84f3ff60 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7fd74ac54790 @ 436)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #4   559f84f3fee0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7fd74ac59310 @ 13)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #5   7ffca0d1fb70 b   self-hosted:261 (7fd74afc1dc0 @ 223)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #6   559f84f3fe60 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7fd74ac59280 @ 64)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #7   559f84f3fde0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7fd74ac593a0 @ 87)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #8   7ffca0d20ca0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #9   7ffca0d21890 b   resource:///org/gnome/shell/ui/sessionMode.js:206 (7fd74ab40ee0 @ 254)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #10   7ffca0d22500 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #11   559f84f3fc98 i   resource:///org/gnome/shell/ui/sessionMode.js:175 (7fd74ab40d30 @ 100)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #12   7ffca0d23470 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #13   559f84f3fc00 i   resource:///org/gnome/shell/ui/screenShield.js:922 (7fd74ab22e50 @ 55)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #14   7ffca0d243d0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #15   559f84f3fb40 i   self-hosted:975 (7fd74afedf70 @ 392)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #16   559f84f3fab8 i   resource:///org/gnome/shell/ui/tweener.js:91 (7fd74afccf70 @ 37)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #17   559f84f3fa18 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (7fd74afdd790 @ 54)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #18   559f84f3f8f8 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:342 (7fd74afdd820 @ 1742)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #19   559f84f3f868 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:355 (7fd74afdd8b0 @ 100)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #20   559f84f3f7f0 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:370 (7fd74afdd940 @ 10)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #21   7ffca0d27000 b   resource:///org/gnome/gjs/modules/signals.js:128 (7fd74afc18b0 @ 386)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #22   559f84f3f760 i   resource:///org/gnome/shell/ui/tweener.js:207 (7fd74afd9790 @ 159)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #23   7ffca0d27f70 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fd74afb0b80 @ 71)
 9월 12 21:07:29 lettuce org.gnome.Shell.desktop[1690]: #24   559f84f3f6e0 i   resource:///org/gnome/shell/ui/tweener.js:182 (7fd74afd9700 @ 15)
 9월 12 21:07:29 lettuce gnome-shell[1690]: g_object_run_dispose: assertion 'G_IS_OBJECT (object)' failed
 9월 12 21:07:29 lettuce gnome-shell[1690]: ../glib/gobject/gsignal.c:2641: instance '0x559f842e0820' has no handler with id '17132'
 9월 12 21:07:29 lettuce gnome-shell[1690]: ../glib/gobject/gsignal.c:2641: instance '0x559f842e0820' has no handler with id '17133'
 9월 12 21:07:29 lettuce gnome-shell[1690]: Extension "workspaces-to-dock@passingthru67.gmail.com" had error: Error: No signal connection 2 found
```

**Comment by passingthru67** [comment] 2018-09-21 11:56
@demokritos I'll look into this as soon as I can.

**Comment by passingthru67** [comment] 2018-09-26 15:03
@demokritos I just tested the suspend feature on both my Arch desktop and laptop. Neither one seems to be giving any issues with WtD on Gnome 3.30.

Are you using the latest github master branch? Please download the latest branch again and let me know how it works. I've committed some changes in the last few days.

If the trouble persists, I'll need some more information to duplicate your setup.

1) What other extensions do you have installed?
2) How do you have WtD configured? Please provide a dump of your WtD configuration by typing the following in the command line .. 

dconf dump /org/gnome/shell/extensions/workspaces-to-dock/ > dconfdump.txt

Then post it here or email it to me at passingthru67@gmail.com.

**Comment by demokritos** [comment] 2018-09-26 15:49
@passingthru67 I just tested the latest version of the master branch and I can confirm the issue is gone.
Thanks for your good work.

**Closed** 2018-09-26 17:05 UTC
