### ISSUE TITLE
[bug] Autohide feature is gone.

### ISSUE THREAD

**Issue by trusktr** [passingthru67/workspaces-to-dock#42] opened 2015-12-01 02:23 UTC
In my Gnome 3.18 installs, by default with no extensions the workspace panel partially hides off the edge of the screen in the overview when there are 3 or more windows (I think that's what triggers it), like this:

![hidden-workspaces](https://cloud.githubusercontent.com/assets/297678/11488336/a0cce5cc-977a-11e5-89b9-2591e7ece083.png)

That feature seems to be gone when enabling workspaces-to-dock. Any way you can add it back?

**Comment by passingthru67** [comment] 2015-12-01 03:26
Actually, I believe the workspace panel is partially hid if there is only one workspace being utilized. And yes, that feature is overridden by design when Workspaces-to-Dock is enabled. This gives users a glimpse of all workspaces and also gives access to the thumbnail caption and taskbar while in overview mode.

**Comment by passingthru67** [comment] 2015-12-01 03:31
I you really need it, I can include an option to add it back.

**Comment by trusktr** [comment] 2015-12-02 08:34
An option would be cool! I'm not really using the captions, app icons, or
task bar (I'm using dash-to-dock for tasks). I'm primarily using the
ability to pop out the workspace panel while on the desktop, which is
convenient compared to having to open the overview first. When I actually
use the overview, it's usually for navigating Windows in the current space
(so the extra space for that is nice) or for launching an app via typing
autocomplete. Second to that I use it to drag Windows between spaces, in
which case the panel will pop out anyways.

/#!/JoePea

**Comment by passingthru67** [comment] 2016-01-20 20:31
This issue has been fixed with commit 060f39f59a30dc509f75f6f36f7b32329fc004ac

**Closed by passingthru67** 2016-01-20 20:31 UTC

**Comment by trusktr** [comment] 2016-01-20 20:35
Released on extensions.gnome.org yet? By the way, how do we update an extension? So far I think just remove first, then re-install with the on switch.

**Comment by The-Panacea-Projects** [comment] 2016-01-21 17:07
Download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (Alt+F2+r). If WTD doesn't show up, you may need to enable the extension using Gnome Tweak tool.

**Comment by passingthru67** [comment] 2016-01-21 17:11
BTW, you will find the overview mode option under the Behavior tab.

**Comment by passingthru67** [comment] 2016-01-22 21:48
I refined the partial hiding of the dock in overview with some animation. It works smoother now.
